name: Build EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pandas numpy openpyxl requests beautifulsoup4 lxml matplotlib

      - name: Build EXE
        run: |
          pyinstaller --onefile GTC_AI_Trading_System_V9_6_2_PRO_FUNDAMENTAL_LOCAL_CACHE_R10_MARKET_SNAPSHOT_FULL_FALLBACK_AND_FAIL_REASON.py

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: GTC_EXE
          path: dist/*.exe
